const internationalization = (language) => {
  switch (language) {
    case 'fr':
      return {
        'settings': 'Paramètres',
        'logout': 'Déconnexion',
        'search': 'Rechercher',
        'filterBy': 'Filtrer par',
        'sortBy': 'Trier par',
        'action': 'Action',
        'adventure': 'Aventure',
        'animation': 'Animation',
        'comedy': 'Comedie',
        'crime': 'Crime',
        'documentary': 'Documentaire',
        'drama': 'Drame',
        'family': 'Famille',
        'fantasy': 'Fantastique',
        'yearAsc': 'Date (Plus récent)',
        'yearDesc': 'Date (Plus vieux)',
        'titleAsc': 'Nom (A-Z)',
        'titleDesc': 'Nom (Z-A)',
        'ratingAsc': 'Etoiles (Meilleur)',
        'ratingDesc': 'Etoiles (Pire)',
        'allCategories': 'Toutes catégories',
        'director': 'Réalisateur',
        'actors': 'Acteurs',
        'availableSubtitles': 'Sous-titres disponibles',
        'validate': 'Valider',
        'unavailableOverview': 'Description indisponible en français',
        'fr': 'Français',
        'en': 'Anglais',
        'es': 'Espagnol',
        'ge': 'Allemand',
        'popularityAsc': 'Plus populaire',
        'popularityDesc': 'Moins populaire'
      }
    case 'es':
      return {
        'settings': 'Configuración',
        'logout': 'Cerrar sesión',
        'search': 'Buscar',
        'filterBy': 'Filtrado por',
        'sortBy': 'Ordenar por',
        'action': 'Action',
        'adventure': 'Aventura',
        'animation': 'Animación',
        'comedy': 'Comedia',
        'crime': 'Crimen',
        'documentary': 'Documental',
        'drama': 'Drama',
        'family': 'Familia',
        'fantasy': 'Fantasía',
        'yearAsc': 'Fecha (Más nuevo)',
        'yearDesc': 'Fecha (Más viejo)',
        'titleAsc': 'Nombre (A-Z)',
        'titleDesc': 'Nombre (Z-A)',
        'ratingAsc': 'Estrellas (mejor)',
        'ratingDesc': 'Estrellas (lo peor)',
        'allCategories': 'Todas las categorías',
        'director': 'Director',
        'actors': 'Actores',
        'availableSubtitles': 'Subtítulos disponibles',
        'validate': 'Validar',
        'unavailableOverview': 'Descripción de la película no disponible en español.',
        'fr': 'Francés',
        'en': 'Inglés',
        'es': 'Español',
        'ge': 'Alemán',
        'popularityAsc': 'Más popular',
        'popularityDesc': 'Menos popular'
      }
    case 'ge':
      return {
        'settings': 'Einstellung',
        'logout': 'Abmeldung',
        'search': 'Suchen',
        'filterBy': 'Filtern nach',
        'sortBy': 'Sortieren nach',
        'action': 'Aktion',
        'adventure': 'Adventure',
        'animation': 'Abenteuer',
        'comedy': 'Komödie',
        'crime': 'Krimi',
        'documentary': 'Doku',
        'drama': 'Drama',
        'family': 'Familien',
        'fantasy': 'Fantasy',
        'yearAsc': 'Datum (neuer)',
        'yearDesc': 'Datum (älter)',
        'titleAsc': 'Name (A-Z)',
        'titleDesc': 'Name (Z-A)',
        'ratingAsc': 'Sterne (Beste)',
        'ratingDesc': 'Sterne (Schlimmste)',
        'allCategories': 'Alle Kategorien',
        'director': 'Regisseur',
        'actors': 'Schauspieler',
        'availableSubtitles': 'Verfügbare Untertitel',
        'validate': 'Bestätigen',
        'unavailableOverview': 'Deutsche Filmbeschreibung nicht verfügbar',
        'fr': 'Französisch',
        'en': 'Englisch',
        'es': 'Spanisch',
        'ge': 'Deutsch',
        'popularityAsc': 'Populärste',
        'popularityDesc': 'Am wenigsten populär'
      }
    default:
      return {
        'settings': 'Settings',
        'logout': 'Logout',
        'search': 'Search',
        'filterBy': 'Filter by',
        'sortBy': 'Sort by',
        'action': 'Action',
        'adventure': 'Adventure',
        'animation': 'Animation',
        'comedy': 'Comedy',
        'crime': 'Crime',
        'documentary': 'Documentary',
        'drama': 'Drama',
        'family': 'Family',
        'fantasy': 'Fantasy',
        'yearAsc': 'Date (Newer)',
        'yearDesc': 'Date (Older)',
        'titleAsc': 'Name (A-Z)',
        'titleDesc': 'Name (Z-A)',
        'ratingAsc': 'Stars (Best)',
        'ratingDesc': 'Stars (Worst)',
        'allCategories': 'All Categories',
        'director': 'Director',
        'actors': 'Actors',
        'availableSubtitles': 'Available subtitles',
        'validate': 'Validate',
        'unavailableOverview': 'Film description unavailable in english',
        'fr': 'French',
        'en': 'English',
        'es': 'Spanish',
        'ge': 'German',
        'popularityAsc': 'Most popular',
        'popularityDesc': 'Least popular'
      }
  }
}

export default internationalization
